name: CI/CD Pipeline

on:
    push:
        branches:
            - main # Trigger this workflow on pushes to the 'main' branch
    workflow_dispatch:

jobs:
    build-and-push-docker-images:
        runs-on: ubuntu-latest # Use the latest Ubuntu runner
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 # Action to check out your repository code
            
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3 # Sets up Docker Buildx for advanced building

            - name: Login in to dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            # IMPORTANT: You will set DOCKER_USERNAME and DOCKER_PASSWORD as GitHub Secrets later
    
            - name: Build and push backend-app image
              uses: docker/build-push-action@v5
              with:
                context: ./backend # Path to the backend Dockerfile context
                push: false # Set to true to push to Docker Hub; for now, we're just building
                tags: sg-esc101/backend-app:latest # Tag the image for future use (replace sg-esc101 with your Docker Hub username)
                # Set build-args for Spring Boot (if you had any specific ones, e.g., JAR_FILE=my-app.jar)
                # build-args: |
                #   JAR_FILE=target/*.jar # Example if you needed to pass specific JAR file name

            - name: Build and push frontend-app image
              uses: docker/build-push-action@v5
              with:
                context: ./frontend # Path to the frontend Dockerfile context
                push: false # Set to true to push to Docker Hub; for now, we're just building
                tags: sg-esc101/frontend-app:latest # Tag the image for future use (replace sg-esc101 with your Docker Hub username)